/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Person;
import static model.Person.persondirectory;
import model.VitalSigns;

/**
 *
 * @author shubhimiradwal
 */
public class PatientJFrame extends javax.swing.JFrame {

    VitalSigns vital= new VitalSigns();
    
    /**
     * Creates new form PatientJFrame
     */
    public PatientJFrame() {
        initComponents();
    }
   // MainJFrame mainframe= new MainJFrame();
  //  PatientJFrame frame= new PatientJFrame();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnpatientprofile = new javax.swing.JButton();
        btnvitalsigns = new javax.swing.JButton();
        btndoctors = new javax.swing.JButton();
        btnencounterhistory = new javax.swing.JButton();
        btndashboardback = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        patientprofilepanel = new javax.swing.JPanel();
        lblpatientprofile = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        pplblname = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        pplblage = new javax.swing.JLabel();
        pplblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        pplblcity = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        pplbladdress = new javax.swing.JLabel();
        patientvitalsignpanel = new javax.swing.JPanel();
        lbladdvitalsigns = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        lbltemperature = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        txtbloodpressure = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        lblweight = new javax.swing.JLabel();
        lblheight = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        btnVitalsignsubmit = new javax.swing.JButton();
        patientdoctorpanel = new javax.swing.JPanel();
        lbldoctorpanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        patientencounterhistorypanel = new javax.swing.JPanel();
        lblpatientencoutnerhistory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpatientprofile.setText("Patient Profile");
        btnpatientprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientprofileActionPerformed(evt);
            }
        });
        jPanel1.add(btnpatientprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 119, -1));

        btnvitalsigns.setText("Vital Signs");
        btnvitalsigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvitalsignsActionPerformed(evt);
            }
        });
        jPanel1.add(btnvitalsigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, 102, -1));

        btndoctors.setText("Doctors");
        btndoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorsActionPerformed(evt);
            }
        });
        jPanel1.add(btndoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 158, 102, -1));

        btnencounterhistory.setText("Encounter History");
        btnencounterhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencounterhistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnencounterhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, -1, -1));

        btndashboardback.setText("<-Back");
        btndashboardback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardbackActionPerformed(evt);
            }
        });
        jPanel1.add(btndashboardback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 380));

        lblpatientprofile.setText("Patient Profile");

        txtname.setText("Name");
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtage.setText("Age");
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });

        txtgender.setText("Gender");

        txtcity.setText("City");

        txtaddress.setText("Address");

        javax.swing.GroupLayout patientprofilepanelLayout = new javax.swing.GroupLayout(patientprofilepanel);
        patientprofilepanel.setLayout(patientprofilepanelLayout);
        patientprofilepanelLayout.setHorizontalGroup(
            patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientprofilepanelLayout.createSequentialGroup()
                .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientprofilepanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblpatientprofile))
                    .addGroup(patientprofilepanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientprofilepanelLayout.createSequentialGroup()
                                .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname)
                                    .addComponent(txtage))
                                .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(patientprofilepanelLayout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(pplblname, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(patientprofilepanelLayout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(pplblage, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(patientprofilepanelLayout.createSequentialGroup()
                                .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(162, 162, 162)
                                .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pplbladdress)
                                    .addComponent(pplblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pplblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        patientprofilepanelLayout.setVerticalGroup(
            patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientprofilepanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblpatientprofile)
                .addGap(50, 50, 50)
                .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pplblname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientprofilepanelLayout.createSequentialGroup()
                        .addComponent(txtage)
                        .addGap(18, 18, 18)
                        .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pplblgender))
                        .addGap(33, 33, 33)
                        .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pplblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(patientprofilepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pplbladdress))
                        .addGap(115, 115, 115))
                    .addGroup(patientprofilepanelLayout.createSequentialGroup()
                        .addComponent(pplblage, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("tab1", patientprofilepanel);

        lbladdvitalsigns.setText("Add Vital Signs");

        lbltemperature.setText("Temperature");

        lblBloodPressure.setText("Blood Pressure");

        txtbloodpressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbloodpressureActionPerformed(evt);
            }
        });

        lblweight.setText("Weight");

        lblheight.setText("Height");

        txtheight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheightActionPerformed(evt);
            }
        });

        btnVitalsignsubmit.setText("Submit");
        btnVitalsignsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalsignsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientvitalsignpanelLayout = new javax.swing.GroupLayout(patientvitalsignpanel);
        patientvitalsignpanel.setLayout(patientvitalsignpanelLayout);
        patientvitalsignpanelLayout.setHorizontalGroup(
            patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientvitalsignpanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltemperature)
                    .addComponent(lblBloodPressure)
                    .addComponent(lblweight, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblheight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTemperature)
                    .addComponent(txtbloodpressure)
                    .addComponent(txtweight)
                    .addComponent(txtheight, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(patientvitalsignpanelLayout.createSequentialGroup()
                .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientvitalsignpanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbladdvitalsigns))
                    .addGroup(patientvitalsignpanelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnVitalsignsubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        patientvitalsignpanelLayout.setVerticalGroup(
            patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientvitalsignpanelLayout.createSequentialGroup()
                .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientvitalsignpanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbltemperature)
                            .addGroup(patientvitalsignpanelLayout.createSequentialGroup()
                                .addComponent(lbladdvitalsigns, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientvitalsignpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblweight)
                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patientvitalsignpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblheight)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnVitalsignsubmit)
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("tab2", patientvitalsignpanel);

        lbldoctorpanel.setText("Available Doctor");

        jLabel1.setText("Name            City               Hospital Name             Contact Info                Book an appointment");

        javax.swing.GroupLayout patientdoctorpanelLayout = new javax.swing.GroupLayout(patientdoctorpanel);
        patientdoctorpanel.setLayout(patientdoctorpanelLayout);
        patientdoctorpanelLayout.setHorizontalGroup(
            patientdoctorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientdoctorpanelLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(lbldoctorpanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientdoctorpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        patientdoctorpanelLayout.setVerticalGroup(
            patientdoctorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientdoctorpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbldoctorpanel)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", patientdoctorpanel);

        lblpatientencoutnerhistory.setText("Encounter History");

        javax.swing.GroupLayout patientencounterhistorypanelLayout = new javax.swing.GroupLayout(patientencounterhistorypanel);
        patientencounterhistorypanel.setLayout(patientencounterhistorypanelLayout);
        patientencounterhistorypanelLayout.setHorizontalGroup(
            patientencounterhistorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientencounterhistorypanelLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lblpatientencoutnerhistory)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        patientencounterhistorypanelLayout.setVerticalGroup(
            patientencounterhistorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientencounterhistorypanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblpatientencoutnerhistory)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", patientencounterhistorypanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -40, 570, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public  void getpatientdetails(List<Person> p)
    {
         for(Person temp: persondirectory)
        {
            
           pplblname.setText(temp.getName());
           pplblage.setText(Integer.toString(temp.getAge()));
           pplblcity.setText(temp.getCity());
           pplblgender.setText(temp.getGender());
           pplbladdress.setText(temp.getAddress());
        }
    }
      
 
    private void btnvitalsignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvitalsignsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
       
    }//GEN-LAST:event_btnvitalsignsActionPerformed

    private void btnpatientprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientprofileActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
         getpatientdetails(persondirectory);
    }//GEN-LAST:event_btnpatientprofileActionPerformed

    private void btndoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_btndoctorsActionPerformed

    private void btnencounterhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencounterhistoryActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnencounterhistoryActionPerformed

    private void btndashboardbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardbackActionPerformed
        // TODO add your handling code here:
        //frame.dispose();
         this.setVisible(false);
        new MainJFrame().setVisible(true);
        
    }//GEN-LAST:event_btndashboardbackActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtbloodpressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbloodpressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbloodpressureActionPerformed

    private void btnVitalsignsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalsignsubmitActionPerformed
        // TODO add your handling code here:
         double temp= Double.parseDouble(txtTemperature.getText());
        double bp= Double.parseDouble(txtbloodpressure.getText());
        double weight= Double.parseDouble(txtweight.getText());
        double height= Double.parseDouble(txtheight.getText());
        
       vital.addvitalsign(temp, bp, weight, height);
        JOptionPane.showMessageDialog(this,"New Person added successfully");
        
    }//GEN-LAST:event_btnVitalsignsubmitActionPerformed

    private void txtheightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheightActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVitalsignsubmit;
    private javax.swing.JButton btndashboardback;
    private javax.swing.JButton btndoctors;
    private javax.swing.JButton btnencounterhistory;
    private javax.swing.JButton btnpatientprofile;
    private javax.swing.JButton btnvitalsigns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lbladdvitalsigns;
    private javax.swing.JLabel lbldoctorpanel;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lblpatientencoutnerhistory;
    private javax.swing.JLabel lblpatientprofile;
    private javax.swing.JLabel lbltemperature;
    private javax.swing.JLabel lblweight;
    private javax.swing.JPanel patientdoctorpanel;
    private javax.swing.JPanel patientencounterhistorypanel;
    private javax.swing.JPanel patientprofilepanel;
    private javax.swing.JPanel patientvitalsignpanel;
    private javax.swing.JLabel pplbladdress;
    private javax.swing.JLabel pplblage;
    private javax.swing.JLabel pplblcity;
    private javax.swing.JLabel pplblgender;
    private javax.swing.JLabel pplblname;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbloodpressure;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
