/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Doctor;
import model.Person;

/**
 *
 * @author user
 */
public class AddDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctorJPanel
     */
    Person person = new Person();
    Doctor doctor = new Doctor();
    public AddDoctorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        comboBoxGender = new javax.swing.JComboBox<>();
        lblHouse = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblPhysicianType = new javax.swing.JLabel();
        txtPhysicianType = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblHospitalName = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 51));
        lblName.setText("NAME");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 111, -1));

        txtName.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 137, -1));

        lblGender.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 51, 51));
        lblGender.setText("GENDER");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 111, -1));

        comboBoxGender.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        add(comboBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 137, -1));

        lblHouse.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblHouse.setForeground(new java.awt.Color(0, 51, 51));
        lblHouse.setText("HOUSE");
        add(lblHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 111, -1));

        txtHouse.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        add(txtHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 137, -1));

        lblCity.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 51, 51));
        lblCity.setText("CITY");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 111, -1));

        txtCity.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 137, -1));

        lblPhysicianType.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblPhysicianType.setForeground(new java.awt.Color(0, 102, 102));
        lblPhysicianType.setText("PHYSICIAN TYPE");
        add(lblPhysicianType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        txtPhysicianType.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        add(txtPhysicianType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 137, -1));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, 40));

        lblHospitalName.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblHospitalName.setForeground(new java.awt.Color(0, 51, 51));
        lblHospitalName.setText("HOSPITAL NAME");
        add(lblHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        txtHospitalName.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        add(txtHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 137, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String name = txtName.getText();
        String gender = (String) comboBoxGender.getSelectedItem();
        String physicianType = txtPhysicianType.getText();
        String house = txtHouse.getText();
        String city = txtCity.getText();
        String hospitalName = txtHospitalName.getText();
        
        doctor.addNewDoctors(name, gender, physicianType, house, city, hospitalName);
        
        String username = name;
        String password = name;
        String usertype = "doctor";
        System.out.println("=======CreateDoctorJPanel================="+username+"=="+password+"=="+usertype);
        person.addNewPerson(username, password, usertype, name, ABORT, gender, house, city, physicianType, hospitalName);
        for(Person per: Person.getPersonDirectory()){
            System.out.println(per.getName()+per.getPassword()+per.getCity());
        }
        JOptionPane.showMessageDialog(this, "Doctor added successfuly");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxGender;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhysicianType;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhysicianType;
    // End of variables declaration//GEN-END:variables
}
