/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Patient;
import model.Person;

/**
 *
 * @author user
 */
public class AddPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPatientJPanel
     */
    Person person = new Person();
    Patient patient = new Patient();
    public AddPatientJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHouse = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();
        comboBoxGender = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHouse.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblHouse.setForeground(new java.awt.Color(0, 51, 51));
        lblHouse.setText("HOUSE");
        add(lblHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 157, 23));
        add(txtHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 157, -1));

        lblCity.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 51, 51));
        lblCity.setText("CITY");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 157, 23));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 157, -1));

        lblAge.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 51, 51));
        lblAge.setText("AGE");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 157, 23));

        lblName.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 51));
        lblName.setText("NAME");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 157, 23));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 157, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 157, -1));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 120, 40));

        lblGender.setFont(new java.awt.Font("Academy Engraved LET", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 51, 51));
        lblGender.setText("GENDER");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 157, 23));

        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        add(comboBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 157, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String name = txtName.getText();
        int age = Integer.parseInt(txtAge.getText());
        String gender = (String) comboBoxGender.getSelectedItem();
        String house = txtHouse.getText();
        String city = txtCity.getText();
        
        patient.addNewPatients(name, age, gender, house, city);

        String username = name;
        String password = name;
        String usertype = "patient";
        System.out.println("=======CreatePatientrJPanel================="+username+"=="+password+"=="+usertype);
        person.addNewPerson(username, password, usertype, name, age, gender, house, city, "NoPhysicianType", "NoHospitalName");
        for(Person per: Person.getPersonDirectory()){
            System.out.println("Person name- "+per.getName()+"Person password- "+per.getPassword()+"Person city- "+per.getCity()+"Person usertype- "+per.getUserType());
        }
        JOptionPane.showMessageDialog(this, "Patient added successfuly");

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxGender;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
