/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HospitalAdmin;

/**
 *
 * @author user
 */
public class ShowHospitalAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowHospitalAdminJPanel
     */
    HospitalAdmin ha = new HospitalAdmin();
   
    public ShowHospitalAdminJPanel() {
        initComponents();
       
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospitalAdmins = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtHospitalName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        comboGender = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHospitalAdmins.setBackground(new java.awt.Color(51, 255, 255));
        tblHospitalAdmins.setForeground(new java.awt.Color(204, 255, 255));
        tblHospitalAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "HospitalName", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHospitalAdmins.setGridColor(new java.awt.Color(153, 255, 255));
        tblHospitalAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHospitalAdminsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHospitalAdmins);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 24, 630, 110));

        lblName.setForeground(new java.awt.Color(0, 102, 102));
        lblName.setText("NAME");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 153, 114, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 150, 106, -1));

        lblGender.setForeground(new java.awt.Color(0, 102, 102));
        lblGender.setText("GENDER");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 201, 114, -1));

        lblHospitalName.setForeground(new java.awt.Color(0, 102, 102));
        lblHospitalName.setText("HOSPITAL NAME");
        add(lblHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 256, 114, -1));

        lblCity.setForeground(new java.awt.Color(0, 102, 102));
        lblCity.setText("CITY");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 312, 114, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 309, 106, -1));

        txtHospitalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalNameActionPerformed(evt);
            }
        });
        add(txtHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 250, 106, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 198, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 198, -1, -1));

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 198, 106, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalNameActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtHospitalNameActionPerformed

    private void tblHospitalAdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHospitalAdminsMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblHospitalAdmins.getSelectedRow();     
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHospitalAdmins.getModel();
        
        HospitalAdmin selectedHospitalAdmin = (HospitalAdmin) model.getValueAt(selectedRowIndex, 0);
        System.out.println(selectedHospitalAdmin);
        
        txtName.setText(selectedHospitalAdmin.getName());
        comboGender.setSelectedItem(selectedHospitalAdmin.getGender());
        txtHospitalName.setText(selectedHospitalAdmin.getHospitalName());
        txtCity.setText(selectedHospitalAdmin.getCity());

    }//GEN-LAST:event_tblHospitalAdminsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblHospitalAdmins.getModel();
        int selectedRowIndex = tblHospitalAdmins.getSelectedRow();
            
        if (tblHospitalAdmins.getSelectedRowCount()==1){
            //-- if single row is selected than update--
            String name = txtName.getText();
            String gender = (String) comboGender.getSelectedItem();
            String hospitalName = txtHospitalName.getText();
            String city = txtCity.getText();
            
            HospitalAdmin updateHospitalAdmin = new HospitalAdmin();
            //-- set updated value on the table row
            updateHospitalAdmin.setName(name);
            updateHospitalAdmin.setGender(gender);
            updateHospitalAdmin.setHospitalName(hospitalName);
            updateHospitalAdmin.setCity(city);
            ha.updateHospitalAdmin(updateHospitalAdmin,selectedRowIndex);
            populateTable();
            
            JOptionPane.showMessageDialog(this, "Data Updated Successfully ");
    }   
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblHospitalAdmins.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this,"please select a row");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHospitalAdmins.getModel();
        HospitalAdmin selectedHospitalAdmin = (HospitalAdmin) model.getValueAt(selectedRowIndex, 0);
        
        ha.deleteHospitalAdmin(selectedHospitalAdmin);
        JOptionPane.showMessageDialog(this,"employee deleted");
        
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblHospitalAdmins;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblHospitalAdmins.getModel();
        model.setRowCount(0);
        
        for(HospitalAdmin ha: HospitalAdmin.getHospitalDirectory()){
            Object[] row = new Object[4];
            row[0] = ha;
            row[1] = ha.getGender();
            row[2] = ha.getHospitalName();
            row[3] = ha.getCity();
            model.addRow(row);
        }
        
    }
}
